<?php

return [

    /*
        Description
    */

    'Geographics_intro' => 'Understanding the physical and spatial characteristics of our planet, and how we interact with it and move around on it, can bring valuable insights into how we can best manage resources while at the same time, respond to people’s needs.',
    'Environment_intro' => 'Environmental data helps us better understand the complex inter-relationships between humans and everything around us, giving insight into the drivers, pressures and impacts of our societies on the environment, and helping find solutions for more equitable and sustainable living.',
    'Transport_intro' => 'In an increasingly mobile world, efficient and well-functioning transport systems are vital for both businesses and individuals. By understanding how, why and when people and goods move, we can optimise current systems, develop innovative solutions, and shape the transport networks of tomorrow.',
    'People_intro' => 'Data about the characteristics and behaviour of individuals and groups of people is critical to public and private sector entities who want to better understand motivations and needs, identify challenges and find solutions, and overall, make more strategic use of resources.',
    'Agriculture_intro' => 'The use of data in primary industries like agriculture, mining, forestry and fishing is gathering momentum, and is on course to reshape the sector, enabling players to optimise their own planning and productivity while better managing resources.',
    'Energy_intro' => 'In today’s energy environment, seizing the potential of data can help us improve and optimise current activities, contribute to better end-to-end management across the energy sector, and also help us design and implement sustainable power-generating activities that meet the needs of future generations.',
    'Economy_intro' => 'Economic data on the production, distribution and consumption of goods and services across sectors, industries and locations has long helped investors understand how well the economy is functioning under certain conditions, predict and react to market changes, and make informed business decisions.',
    'Supply_Chain_intro' => 'With supply chain management becoming increasingly complex, companies can leverage data to become more responsive and maximise efficiency. And by better understanding customer and market trends, supply chain managers can predict and proactively strategise supply chain-related activities.',
    'Geographics_overview' => 'The Geographics community includes data that helps us better understand the Earth’s physical characteristics and how we make use of it, in order to make decisions about urban planning, business development and more.',
    'Environment_overview' => 'The Environment community includes data that can help us better understand the complex inter-relationships between humans and the natural world, and as a result, contribute to protecting both human health and the environment.',
    'Transport_overview' => 'The Transport community includes data about the movement of people and goods, traffic, transport safety and the transport industry in general. By understanding behaviours, choices and needs, we can develop the policies and solutions of the future.',
    'People_overview' => 'The People community includes data about the characteristics and behaviour of individuals and groups of people that can provide valuable insights into how they live, and how we can better meet their current and future needs.',
    'Agriculture_overview' => 'The Agriculture community includes data related to primary industries like agriculture, mining, forestry and fishing that can help public and private sector entities optimise their own planning and productivity while better managing resources.',
    'Energy_overview' => 'The Energy community includes data related to the production, supply, consumption, trading and costs of energy, which can used to improve and optimise current activities, but also to design and implement the sustainable power-generating activities of the future.',
    'Economy_overview' => 'The Economy community includes data that can help us better judge the overall health of an economy, and the direction it is going. This can pave the way for an investment strategy that will fit future market conditions.',
    'Supply_Chain_overview' => 'The Supply chain community includes data that can help companies respond to the challenges of today’s ever-changing supply chain management landscape, from sales, inventory, and operations planning, right through to the end customer.',
    'company_logo_tooltip' => 'Please choose a high-quality JPG or PNG file, with a white or transparent background. Minimum dimensions 430 x 240 pixels; maximum file size 50KB.',
    'what_offer_tooltip' => 'Give a concise description of the data e.g. Satellite imagery of road networks so that potential buyers understand what you have to offer.',
    'offer_region_tooltip' => 'You can add more detailed regions or countries later when you define specific data product for this data offer',
    'offer_sample_tooltip' => 'Uploading some screenshots or other representations of the data can help potential buyers better understand the quality and relevance of the data you can offer. You could upload an image file or pdf showing a sample of a possible data product.',
    'offer_sample_file_tooltip' => 'You can upload up to 3 files of any kind. Maximum file size XMB.',
    'offer_usecase_tooltip' => 'Providing some use cases helps potential buyers understand how they might be able to use your data to enrich their business.',
    'offer_description_tooltip' => 'Describing the data offer in more detail helps potential buyers decide whether or not they are interested in your offer. For example, you might want to explain how the data is collected, whether or not it requires special processing etc.',
    'community_Geographics_tooltip' => 'Data about geographic locations, physical and human characteristics of places, human-environment interaction, movement of people good and ideas.',
    'community_Environment_tooltip' => 'Data on natural resources, emissions, biodiversity, waste and recycling, hazardous substances, resource productivity, taxes and climate change.',
    'community_Transport_tooltip' => 'Data about transport of goods and people, traffic, safety and the transport industry in general, including employment, infrastructure and equipment.',
    'community_People_tooltip' => 'Data about population, health, education and training, labour market, income, social inclusion and living conditions, culture, crime and equality.',
    'community_Agriculture_tooltip' => 'Data about economic accounts for agriculture, forestry and fisheries, prices and indices, input and output, organic farming and agri-environmental data.',
    'community_Energy_tooltip' => 'Data about energy balances, stocks and supply, transformation and consumption, energy prices, and energy infrastructure and capacities.',
    'community_Economy_tooltip' => 'Data about national accounts, government finance and EDP, exchange and interest rates, economic globalisation, digital economy and society, and commerce.',
    'community_Supply_Chain_tooltip' => 'Data related to supply chains in the automotive, chemical, electronics, food and beverage, pharmaceutical and retail sectors.',
    'which_community_tooltip' => "<p class='text-bold mb-0'>Geographics</p><p>Data about geographic locations, physical and human characteristics of places, human-environment interaction, movement of people good and ideas.</p><p class='text-bold mb-0'>Environment</p><p>Data on natural resources, emissions, biodiversity, waste and recycling, hazardous substances, resource productivity, taxes and climate change.</p><p class='text-bold mb-0'>Transport</p><p>Data about transport of goods and people, traffic, safety and the transport industry in general, including employment, infrastructure and equipment.</p><p class='text-bold mb-0'>People</p><p>Data about population, health, education and training, labour market, income, social inclusion and living conditions, culture, crime and equality.</p><p class='text-bold mb-0'>Agriculture</p><p>Data about economic accounts for agriculture, forestry and fisheries, prices and indices, input and output, organic farming and agri-environmental data.</p><p class='text-bold mb-0'>Energy</p><p>Data about energy balances, stocks and supply, transformation and consumption, energy prices, and energy infrastructure and capacities.</p><p class='text-bold mb-0'>Economy</p><p>Data about national accounts, government finance and EDP, exchange and interest rates, economic globalisation, digital economy and society, and commerce.</p><p class='text-bold mb-0'>Supply chain</p><p>Data related to supply chains in the automotive, chemical, electronics, food and beverage, pharmaceutical and retail sectors.</p>",
    'offer_image_tooltip' => "Please choose a high-quality JPG file. Minimum dimensions 1920 x 1024 pixels; maximum file size 500KB.
    If you choose to upload an image, please make sure you have the necessary rights to use it.",
    'what_product_tooltip' => 'Give a descriptive title e.g. Satellite imagery of road networks – GSD 1-5m.',
    'product_datacover_tooptip' => 'You can select one or more regions, or add individual countries.',
    'product_data_provided_tooptip' => 'You can provide data as a one-off file or stream that can be accessed during a defined period, or as an API that can be called during a defined period.',
    'product_pricing_tooptip' => 'When you sell data, Databroker charges a transaction fee of 10% of the sale price. This means that, at the end of the 30-day warranty period we credit your wallet with the earnings, minus the 10% transaction fee.',
    'product_potential_buyer_tooptip' => 'Potential buyers see this information alongside the title of your data product. If there is anything they need to know about this specific data product, you can mention it here.',
    'product_license_url_tooptip' => 'The data you are selling is an asset that needs to be protected. Which is why the rights to use that data are governed by a licence, configured by you. To purchase your data, the buyer needs to accept the terms of the data licence, and is then legally bound to comply with your conditions of use.',
];
