@extends('layouts.app')

@section('content')       
<div class="container-fluid app-wapper bg-pattern-side app-wapper-cookie-policy">
    <div class="container">
        <div class="mt-30">
            <h1 class="text-primary text-center text-bold">{{ trans('about.cookie_policy') }}</h1>
            <div class="row">
            	<div class="col-md-12">
            		<div class="mt-50">
            			<h3 class="ml-20 text-bold text-uppercase">1. What are cookies?</h3><br>
	            		<p class="fs-18">Cookies are small (text) files, which are stored onto your device by the server of the website you visit. Cookies contain information used by the server to:</p>
	            		<ul class="fs-18 list-style-none">
	            			<li>-	Optimize functionality of the website.</li>
	            			<li>-	Optimize rendering of the website.</li>
	            			<li>-	Retain and reuse selected preferences.</li>
	            			<li>-	Analyze visitor’s behavior.</li>
	            			<li>-	Provide targeted advertisement.</li>
	            		</ul>
	            		<p class="fs-18">Cookies typically do not register any personal data, such as your name, address, phone number, email address or other data that can be traced back to you.</p>
	            		<p class="fs-18">If you wish, you can configure most browsers to reject cookies or to notify you when cookies are being sent.</p>
            		</div>
            		<div class="mt-50">
            			<h3 class="ml-20 text-bold text-uppercase">2. Which cookies do we use?</h3><br>
	            		<p class="fs-18">A distinction can be made in the types of cookies in relation to the controlling and processing of the cookies:</p>
	            		<ul class="fs-18 list-style-none">
	            			<li>
	            				<p class="fs-18">- First party cookies:</p>
	            				<ul class="fs-18 list-style-circle">
	            					<li>Cookies which are fully controlled by SettleMint NV.</li>
	            				</ul>
	            			</li>
	            			<li>
	            				<p class="fs-18">- Third party cookies:</p>
	            				<ul class="fs-18 list-style-circle">
	            					<li>Cookies which are controlled by a third party related to SettleMint; e.g. Google or Facebook.</li>
	            				</ul>
	            			</li>
	            		</ul>
	            		<p class="fs-18">A second distinction can be made based on the purpose of cookies:</p>
	            		<ul class="fs-18 list-style-none">
	            			<li>
	            				<p class="fs-18">- Necessary cookies:</p>
	            				<ul class="fs-18 list-style-circle">
	            					<li>Cookies are required to use the website.</li>
	            				</ul>
	            			</li>
	            			<li>
	            				<p class="fs-18">- Functional cookies:</p>
	            				<ul class="fs-18 list-style-circle">
	            					<li>Cookies are facilitating the use of the website and provide you a more personalized experience.</li>
	            				</ul>
	            			</li>
	            			<li>
	            				<p class="fs-18">- Analytical cookies:</p>
	            				<ul class="fs-18 list-style-circle">
	            					<li>Cookies are used to compile visitor statistics to provide a better understanding of the functioning of the website.</li>
	            				</ul>
	            			</li>
	            			<li>
	            				<p class="fs-18">- Marketing cookies:</p>
	            				<ul class="fs-18 list-style-circle">
	            					<li>Cookies can monitor internet user behavior to show personalized online advertisements and customized content.</li>
	            				</ul>
	            			</li>
	            		</ul>
	            		<p class="fs-18">Necessary, functional and analytical cookies, whether first or third party, are always used and placed when visiting our website. We ask for your consent to use and place first party cookies related to marketing purposes.</p>
            		</div>
            		<div class="mt-50">
            			<h3 class="ml-20 text-bold text-uppercase">3. Overview of cookies used</h3><br>
	            		<p class="fs-18">First party cookies:</p>
	            		<table class="table table-border">
	            			<thead>
	            				<tr>
	            					<td>#</td>
	            					<td>Name</td>
	            					<td>Domain</td>
	            					<td>Category</td>
	            					<td>Function</td>
	            				</tr>
	            			</thead>
	            			<tbody>
	            				<tr>
	            					<td>1</td>
	            					<td>(unnamed)</td>
	            					<td>.databrokerdao.com</td>
	            					<td></td>
	            					<td></td>
	            				</tr>
	            				<tr>
	            					<td>2</td>
	            					<td>__cfduid</td>
	            					<td>.databrokerdao.com</td>
	            					<td>Necessary</td>
	            					<td>Identification of trusted web traffic.</td>
	            				</tr>
	            				<tr>
	            					<td>3</td>
	            					<td>_fbp</td>
	            					<td>.databrokerdao.com</td>
	            					<td>Marketing</td>
	            					<td>Used by Facebook to deliver advertisement.</td>
	            				</tr>
	            				<tr>
	            					<td>4</td>
	            					<td>_ga</td>
	            					<td>.databrokerdao.com</td>
	            					<td>Statistics</td>
	            					<td>Unique ID registration for statistical data generation.</td>
	            				</tr>
	            				<tr>
	            					<td>5</td>
	            					<td>_gat</td>
	            					<td>.databrokerdao.com</td>
	            					<td>Statistics</td>
	            					<td>Used by Google Analytics to throttle request rate.</td>
	            				</tr>
	            				<tr>
	            					<td>6</td>
	            					<td>_gat_UA-79513961-1</td>
	            					<td>.databrokerdao.com</td>
	            					<td></td>
	            					<td></td>
	            				</tr>
	            				<tr>
	            					<td>7</td>
	            					<td>_gid</td>
	            					<td>.databrokerdao.com</td>
	            					<td>Statistics</td>
	            					<td>Unique ID registration for statistical data generation.</td>
	            				</tr>
	            				<tr>
	            					<td>8</td>
	            					<td>_hjCookieTest</td>
	            					<td>.databrokerdao.com</td>
	            					<td></td>
	            					<td></td>
	            				</tr>
	            				<tr>
	            					<td>9</td>
	            					<td>_hjid (HTML)</td>
	            					<td>.databrokerdao.com</td>
	            					<td></td>
	            					<td></td>
	            				</tr>
	            				<tr>
	            					<td>10</td>
	            					<td>_hjid (HTTP)</td>
	            					<td>.databrokerdao.com</td>
	            					<td></td>
	            					<td></td>
	            				</tr> 
	            				<tr>
	            					<td>11</td>
	            					<td>_hjIncludedInSample</td>
	            					<td>.databrokerdao.com</td>
	            					<td>Marketing</td>
	            					<td>Determines if the user's navigation should be registered in a certain statistical placeholder.</td>
	            				</tr>
	            				<tr>
	            					<td>12</td>
	            					<td>MCPopupClosed</td>
	            					<td>.databrokerdao.com</td>
	            					<td></td>
	            					<td></td>
	            				</tr>
	            			</tbody>
	            		</table>
	            		<br>
	            		<p class="fs-18">Third party cookies:</p>
	            		<table class="table table-border">
	            			<thead>
	            				<tr>
	            					<td>#</td>
	            					<td>Name</td>
	            					<td>Domain</td>
	            					<td>Category</td>
	            				</tr>
	            			</thead>
	            			<tbody>
	            				<tr>
	            					<td>1</td>
	            					<td>BizoID</td>
	            					<td>.ads.linkedin.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>2</td>
	            					<td>lang</td>
	            					<td>.ads.linkedin.com</td>
	            					<td>Functionality</td>
	            				</tr>
	            				<tr>
	            					<td>3</td>
	            					<td>__cfduid</td>
	            					<td>.calendly.com</td>
	            					<td>Necessary</td>
	            				</tr>
	            				<tr>
	            					<td>4</td>
	            					<td>_calendly_session</td>
	            					<td>.calendly.com</td>
	            					<td>Functionality</td>
	            				</tr>
	            				<tr>
	            					<td>5</td>
	            					<td>keen</td>
	            					<td>.calendly.com</td>
	            					<td>To be determined</td>
	            				</tr>
	            				<tr>
	            					<td>6</td>
	            					<td>prodperfect_session</td>
	            					<td>.calendly.com</td>
	            					<td>Functionality</td>
	            				</tr>
	            				<tr>
	            					<td>7</td>
	            					<td>__cfduid</td>
	            					<td>.cloudflare.com</td>
	            					<td>Necessary</td>
	            				</tr>
	            				<tr>
	            					<td>8</td>
	            					<td>DSID</td>
	            					<td>.doubleclick.net</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>9</td>
	            					<td>id</td>
	            					<td>.doubleclick.net</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>10</td>
	            					<td>IDE</td>
	            					<td>.doubleclick.net</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>11</td>
	            					<td>test_cookie</td>
	            					<td>.doubleclick.net</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>12</td>
	            					<td>(unnamed)</td>
	            					<td>.facebook.com</td>
	            					<td>To be determined</td>
	            				</tr>
	            				<tr>
	            					<td>13</td>
	            					<td>act</td>
	            					<td>.facebook.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>14</td>
	            					<td>c_user</td>
	            					<td>.facebook.com</td>
	            					<td>Functionality</td>
	            				</tr>
	            				<tr>
	            					<td>15</td>
	            					<td>datr</td>
	            					<td>.facebook.com</td>
	            					<td>Necessary</td>
	            				</tr>
	            				<tr>
	            					<td>16</td>
	            					<td>fr</td>
	            					<td>.facebook.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>17</td>
	            					<td>presence</td>
	            					<td>.facebook.com</td>
	            					<td>Functionality</td>
	            				</tr>
	            				<tr>
	            					<td>18</td>
	            					<td>sb</td>
	            					<td>.facebook.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>19</td>
	            					<td>spin</td>
	            					<td>.facebook.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>20</td>
	            					<td>tr</td>
	            					<td>.facebook.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>21</td>
	            					<td>wd</td>
	            					<td>.facebook.com</td>
	            					<td>Functionality</td>
	            				</tr>
	            				<tr>
	            					<td>22</td>
	            					<td>xs</td>
	            					<td>.facebook.com</td>
	            					<td>Necessary</td>
	            				</tr>
	            				<tr>
	            					<td>23</td>
	            					<td>1P_JAR</td>
	            					<td>.google.be</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>24</td>
	            					<td>APISID</td>
	            					<td>.google.be</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>25</td>
	            					<td>CONSENT</td>
	            					<td>.google.be</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>26</td>
	            					<td>HSID</td>
	            					<td>.google.be</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>27</td>
	            					<td>NID</td>
	            					<td>.google.be</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>28</td>
	            					<td>SAPISID</td>
	            					<td>.google.be</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>29</td>
	            					<td>SID</td>
	            					<td>.google.be</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>30</td>
	            					<td>SSID</td>
	            					<td>.google.be</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>31</td>
	            					<td>1P_JAR</td>
	            					<td>.google.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>32</td>
	            					<td>ads/ga-audiences</td>
	            					<td>.google.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>33</td>
	            					<td>AID</td>
	            					<td>.google.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>34</td>
	            					<td>ANID</td>
	            					<td>.google.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>35</td>
	            					<td>APISID</td>
	            					<td>.google.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>36</td>
	            					<td>CONSENT</td>
	            					<td>.google.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>37</td>
	            					<td>DV</td>
	            					<td>.google.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>38</td>
	            					<td>HSID</td>
	            					<td>.google.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>39</td>
	            					<td>NID</td>
	            					<td>.google.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>40</td>
	            					<td>SAPISID</td>
	            					<td>.google.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>41</td>
	            					<td>SID</td>
	            					<td>.google.com</td>
	            					<td>Statistics</td>
	            				</tr>
	            				<tr>
	            					<td>42</td>
	            					<td>SIDCC</td>
	            					<td>.google.com</td>
	            					<td>Statistics</td>
	            				</tr>
	            				<tr>
	            					<td>43</td>
	            					<td>SSID</td>
	            					<td>.google.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>44</td>
	            					<td>1P_JAR</td>
	            					<td>.gstatic.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>45</td>
	            					<td>CONSENT</td>
	            					<td>.gstatic.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>46</td>
	            					<td>__hstc</td>
	            					<td>.hotjar.com</td>
	            					<td>Statistics</td>
	            				</tr>
	            				<tr>
	            					<td>47</td>
	            					<td>_fbp</td>
	            					<td>.hotjar.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>48</td>
	            					<td>_ga</td>
	            					<td>.hotjar.com</td>
	            					<td>Statistics</td>
	            				</tr>
	            				<tr>
	            					<td>49</td>
	            					<td>_gaexp</td>
	            					<td>.hotjar.com</td>
	            					<td>Statistics</td>
	            				</tr>
	            				<tr>
	            					<td>50</td>
	            					<td>_gcl_au</td>
	            					<td>.hotjar.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>51</td>
	            					<td>ajs_anonymous_id</td>
	            					<td>.hotjar.com</td>
	            					<td>Functionality</td>
	            				</tr>
	            				<tr>
	            					<td>52</td>
	            					<td>ajs_group_id</td>
	            					<td>.hotjar.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>53</td>
	            					<td>ajs_user_id</td>
	            					<td>.hotjar.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>54</td>
	            					<td>hubspotutk</td>
	            					<td>.hotjar.com</td>
	            					<td>Statistics</td>
	            				</tr>
	            				<tr>
	            					<td>55</td>
	            					<td>__ssid</td>
	            					<td>.linkedin.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>56</td>
	            					<td>__utma</td>
	            					<td>.linkedin.com</td>
	            					<td>Functionality</td>
	            				</tr>
	            				<tr>
	            					<td>57</td>
	            					<td>_ga</td>
	            					<td>.linkedin.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>58</td>
	            					<td>_guid</td>
	            					<td>.linkedin.com</td>
	            					<td>Statistics</td>
	            				</tr>
	            				<tr>
	            					<td>59</td>
	            					<td>_lipt</td>
	            					<td>.linkedin.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>60</td>
	            					<td>aam_uuid</td>
	            					<td>.linkedin.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>61</td>
	            					<td>AMCV_14215E3D5995C57C0A495C55%40AdobeOrg</td>
	            					<td>.linkedin.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>62</td>
	            					<td>AMCVS_14215E3D5995C57C0A495C55%40AdobeOrg</td>
	            					<td>.linkedin.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>63</td>
	            					<td>bcookie</td>
	            					<td>.linkedin.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>64</td>
	            					<td>bscookie</td>
	            					<td>.linkedin.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>65</td>
	            					<td>ELOQUA</td>
	            					<td>.linkedin.com</td>
	            					<td>Functionality</td>
	            				</tr>
	            				<tr>
	            					<td>66</td>
	            					<td>lang</td>
	            					<td>.linkedin.com</td>
	            					<td>Preferences</td>
	            				</tr>
	            				<tr>
	            					<td>67</td>
	            					<td>lang</td>
	            					<td>.linkedin.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>68</td>
	            					<td>li_oatml</td>
	            					<td>.linkedin.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>69</td>
	            					<td>liap</td>
	            					<td>.linkedin.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>70</td>
	            					<td>lidc</td>
	            					<td>.linkedin.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>71</td>
	            					<td>org_tcphc</td>
	            					<td>.linkedin.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>72</td>
	            					<td>UserMatchHistory</td>
	            					<td>.linkedin.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>73</td>
	            					<td>utag_main</td>
	            					<td>.linkedin.com</td>
	            					<td>Functionality</td>
	            				</tr>
	            				<tr>
	            					<td>74</td>
	            					<td>LOGIN_INFO</td>
	            					<td>.m.youtube.com</td>
	            					<td>Functionality</td>
	            				</tr>
	            				<tr>
	            					<td>75</td>
	            					<td>_derived_epik</td>
	            					<td>.mailchimp.com</td>
	            					<td>Functionality</td>
	            				</tr>
	            				<tr>
	            					<td>76</td>
	            					<td>_fbp</td>
	            					<td>.mailchimp.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>77</td>
	            					<td>_ga</td>
	            					<td>.mailchimp.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>78</td>
	            					<td>_gcl_au</td>
	            					<td>.mailchimp.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>79</td>
	            					<td>_gid</td>
	            					<td>.mailchimp.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>80</td>
	            					<td>_mcid</td>
	            					<td>.mailchimp.com</td>
	            					<td>Necessary</td>
	            				</tr>
	            				<tr>
	            					<td>81</td>
	            					<td>nmstat</td>
	            					<td>.mailchimp.com</td>
	            					<td>Statistics</td>
	            				</tr>
	            				<tr>
	            					<td>82</td>
	            					<td>OptanonAlertBoxClosed</td>
	            					<td>.mailchimp.com</td>
	            					<td>Necessary</td>
	            				</tr>
	            				<tr>
	            					<td>83</td>
	            					<td>OptanonConsent</td>
	            					<td>.mailchimp.com</td>
	            					<td>Necessary</td>
	            				</tr>
	            				<tr>
	            					<td>84</td>
	            					<td>optimizelyEndUserId</td>
	            					<td>.mailchimp.com</td>
	            					<td>Statistics</td>
	            				</tr>
	            				<tr>
	            					<td>85</td>
	            					<td>_AVESTA_ENVIRONMENT</td>
	            					<td>.mc.us16.list-manage.com</td>
	            					<td>Preferences</td>
	            				</tr>
	            				<tr>
	            					<td>86</td>
	            					<td>GPS</td>
	            					<td>.youtube.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>87</td>
	            					<td>LOGIN_INFO</td>
	            					<td>.youtube.com</td>
	            					<td>Functionality</td>
	            				</tr>
	            				<tr>
	            					<td>88</td>
	            					<td>PREF</td>
	            					<td>.youtube.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>89</td>
	            					<td>VISITOR_INFO1_LIVE</td>
	            					<td>.youtube.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>90</td>
	            					<td>YSC</td>
	            					<td>.youtube.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>91</td>
	            					<td>yt-remote-cast-installed</td>
	            					<td>.youtube.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>92</td>
	            					<td>yt-remote-connected-devices</td>
	            					<td>.youtube.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>93</td>
	            					<td>yt-remote-device-id</td>
	            					<td>.youtube.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>94</td>
	            					<td>yt-remote-fast-check-period</td>
	            					<td>.youtube.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>95</td>
	            					<td>yt-remote-session-app</td>
	            					<td>.youtube.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            				<tr>
	            					<td>96</td>
	            					<td>yt-remote-session-name</td>
	            					<td>.youtube.com</td>
	            					<td>Marketing</td>
	            				</tr>
	            			</tbody>
	            		</table>
            		</div>
            	</div>
            </div>
        </div>
    </div>
</div>
@endsection